# Generated by Django 3.2.7 on 2021-09-10 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountdata',
            name='account_id',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
