# Generated by Django 3.2.7 on 2021-09-10 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_users', '0002_alter_accountdata_account_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountdata',
            name='account_number',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
