# Generated by Django 3.2.7 on 2021-09-10 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_users', '0003_alter_accountdata_account_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactdata',
            name='contact_id',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='user_id',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
